package pl.jcommerce.moonshine.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

/**
 * Base class for entities. Accessor, mutator, and construction data is being
 * auto generated by Lombok library
 * 
 * @author wipo
 *
 */
@MappedSuperclass
@Data
public class BaseEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@JsonIgnore
	private boolean deleted = false;
}
