package pl.jcommerce.moonshine.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import pl.jcommerce.moonshine.controller.serializator.TwiAddressDeserializer;
import pl.jcommerce.moonshine.controller.serializator.TwiAddressSerializer;

import javax.persistence.Embeddable;

/**
 * Contains physical thermometer address using I2C interface. Serializable by
 * JSON serializable classes. Accessor, mutator, and construction data is being
 * auto generated by Lombok library
 *
 * @author wipo
 * @see TwiAddressSerializer
 * @see TwiAddressDeserializer
 */
@Data
@Embeddable
@RequiredArgsConstructor
@NoArgsConstructor
@JsonDeserialize(using = TwiAddressDeserializer.class)
@JsonSerialize(using = TwiAddressSerializer.class)
public class TwiAddress {

    @NonNull
    private Byte[] physicalAddress;

}
